/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyCoachRouteImport } from './routes/weekly-coach'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MealRouteImport } from './routes/meal'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDailyCoachRouteImport } from './routes/api/daily-coach'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeMealRouteImport } from './routes/api/analyze-meal'

const WeeklyCoachRoute = WeeklyCoachRouteImport.update({
  id: '/weekly-coach',
  path: '/weekly-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MealRoute = MealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyCoachRoute = ApiDailyCoachRouteImport.update({
  id: '/api/daily-coach',
  path: '/api/daily-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeMealRoute = ApiAnalyzeMealRouteImport.update({
  id: '/api/analyze-meal',
  path: '/api/analyze-meal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/weekly-coach': typeof WeeklyCoachRoute
  '/api/analyze-meal': typeof ApiAnalyzeMealRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily-coach': typeof ApiDailyCoachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/weekly-coach': typeof WeeklyCoachRoute
  '/api/analyze-meal': typeof ApiAnalyzeMealRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily-coach': typeof ApiDailyCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/meal': typeof MealRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/weekly-coach': typeof WeeklyCoachRoute
  '/api/analyze-meal': typeof ApiAnalyzeMealRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily-coach': typeof ApiDailyCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/meal'
    | '/onboarding'
    | '/plan'
    | '/weekly-coach'
    | '/api/analyze-meal'
    | '/api/chat'
    | '/api/daily-coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/meal'
    | '/onboarding'
    | '/plan'
    | '/weekly-coach'
    | '/api/analyze-meal'
    | '/api/chat'
    | '/api/daily-coach'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/meal'
    | '/onboarding'
    | '/plan'
    | '/weekly-coach'
    | '/api/analyze-meal'
    | '/api/chat'
    | '/api/daily-coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  MealRoute: typeof MealRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  WeeklyCoachRoute: typeof WeeklyCoachRoute
  ApiAnalyzeMealRoute: typeof ApiAnalyzeMealRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDailyCoachRoute: typeof ApiDailyCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-coach': {
      id: '/weekly-coach'
      path: '/weekly-coach'
      fullPath: '/weekly-coach'
      preLoaderRoute: typeof WeeklyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal': {
      id: '/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof MealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-coach': {
      id: '/api/daily-coach'
      path: '/api/daily-coach'
      fullPath: '/api/daily-coach'
      preLoaderRoute: typeof ApiDailyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-meal': {
      id: '/api/analyze-meal'
      path: '/api/analyze-meal'
      fullPath: '/api/analyze-meal'
      preLoaderRoute: typeof ApiAnalyzeMealRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  MealRoute: MealRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  WeeklyCoachRoute: WeeklyCoachRoute,
  ApiAnalyzeMealRoute: ApiAnalyzeMealRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDailyCoachRoute: ApiDailyCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
